name: Run Integration Tests

on: [push]

jobs:
  test_all:
    runs-on: ubuntu-18.04
    name: Test All
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: actions/checkout@master
      - name: Install Ganache
        run: sudo npm install -g ganache-cli
      - name: Start Ganache
        run: >
          ganache-cli
          --fork https://matic-mainnet-archive-rpc.bwarelabs.com
          --account="${{ secrets.WALLET_PRIVATE_KEY }},1000000000000000000000" &
      - name: What next?
        run: sleep 2
      - name: run test
        env:
          RPC_URI: http://localhost:8545
          POLYGON_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
        run: |
          cd ${GITHUB_WORKSPACE}
          pip install -r dev_requirements.txt
          python -mpytest -v tests
