name: Linting

on: [push]

jobs:
  styles:
    runs-on: ubuntu-18.04
    name: Linting
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: py-actions/flake8@v1